name: E2E Tests

on:
    workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Display Node.js version
        run: node -v
      
      - name: Setup and run tests
        run: |
          cd D:/Development/Work/Projects/AmbergRMS/l3-automationtest-amberg-engr
          npm install
          npm run login
