name: E2E Tests

on:
  workflow_dispatch:

permissions:
    checks: write

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Display Node.js version
        run: node -v
      
      - name: Setup and run tests
        run: |
          cd D:/Development/Work/Projects/AmbergRMS/l3-automationtest-amberg-engr
          npm install --verbose
          npm run login

      - name: Upload test results
        uses: actions/upload-artifact@v2
        if: always()  # this ensures that the results are uploaded even if the test step fails
        with:
          name: junit-results
          path: D:/Development/Work/Projects/AmbergRMS/l3-automationtest-amberg-engr/junit-results/*.xml

  publish-results:
    needs: test  # make sure this job runs after the 'test' job
    runs-on: ubuntu-latest  # this action works best on Linux runners
    steps:
      - name: Download test results
        uses: actions/download-artifact@v2
        with:
          name: junit-results

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()  # this ensures that the results are published even if no XML files are found
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: junit-results/*.xml
