name: Test Submodule Checkout

on:
  workflow_dispatch: 

jobs:
  checkout-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Installer Repo
        uses: actions/checkout@v3

      - name: Checkout Automation Test Repo
        uses: actions/checkout@v3
        with:
          repository: asifarshadullah/test-target-repository
          path: automation-tests

      - name: Verify Automation Test Checkout
        run: |
          cd automation-tests
          chmod +x test-script.sh
          ./test-script.sh
